id: P002991
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:33:01.291381
source_metadata:
  id: bdr:W1KG8936
  title: མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པའི་ཟབ་དོན་ལེགས་པར་བཤད་པ་ཤེར་ཕྱིན་དོན་གསལ་ཁག་གི་མཐའ་དཔྱོད།
  author: ''
  volumes:
    ca6239b425e545bab0bf5241dbc4a2b0:
      image_group_id: I1KG9011
      title: ''
      volume_number: 1
      total_pages: 908
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
