id: P002991
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8936
  title: མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པའི་ཟབ་དོན་ལེགས་པར་བཤད་པ་ཤེར་ཕྱིན་དོན་གསལ་ཁག་གི་མཐའ་དཔྱོད།
  author: ''
  volumes:
    ca6239b425e545bab0bf5241dbc4a2b0:
      image_group_id: I1KG9011
      title: ''
      volume_number: 1
      total_pages: 908
      base_file: v001.txt
