id: I43937C73
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:59:01+00:00'
last_modified: '2022-06-07T16:49:39.842110+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8936
  title: མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པའི་ཟབ་དོན་ལེགས་པར་བཤད་པ་ཤེར་ཕྱིན་དོན་གསལ་ཁག་གི་མཐའ་དཔྱོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    611F:
      image_group_id: I1KG9011
      title: ''
      total_pages: 908
      order: 1
      base_file: 611F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
